version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: peso-tracker-db
    env_file:
      - .env
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data # Volumen persistente para evitar que se borren los datos
      - ./init-db.sql:/docker-entrypoint-initdb.d/init-db.sql # Inicialización de la DB
    networks:
      - peso-network
    restart: unless-stopped

  node-app:
    build: .
    container_name: peso-tracker-api
    env_file:
      - .env
    environment:
      NODE_ENV: ${NODE_ENV}
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      JWT_SECRET: ${JWT_SECRET}
      PORT: ${PORT}
    command: npm run start # Usamos "npm run start" para iniciar la aplicación compilada
    ports:
      - '3000:3000'
    depends_on:
      - postgres
    volumes:
      - ./src:/app/src # Mantiene sincronizada la carpeta src entre host y contenedor
      - /app/node_modules # Para evitar conflictos con node_modules
    networks:
      - peso-network
    restart: unless-stopped

  pgadmin:
    image: dpage/pgadmin4
    container_name: peso-tracker-pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@pesotracker.com
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    ports:
      - '5050:80'
    depends_on:
      - postgres
    networks:
      - peso-network
    restart: unless-stopped

volumes:
  postgres_data: # Volumen persistente para la base de datos

networks:
  peso-network:
    driver: bridge
